### ISSUE TITLE
sysl call parameter parse bug

### ISSUE THREAD

**Issue by nydrani** [anz-bank/sysl#1040]
https://github.com/anz-bank/sysl-go/issues/215

There's a bug related to parsing calls:
This is the json representation:
```
     "param": [
      {
       "name": "input",
       "type": {
        "typeRef": {
         "ref": {
          "appname": {
           "part": [
            "depserver"
           ]
          },
          "path": [
           "HelloRequest"
          ]
         }
        }
       }
      }
     ],
```

Which is parsed from the sysl file:
```
myserverdep[~gRPC]:
    Hello(input <: depserver.HelloRequest)[~gRPC]:
        return ok <: depserver.HelloResponse
```

I believe the "path" should not be HelloResponse and the "appname.part" should be ['depserver', 'HelloRequest']. This 'path' part seems to be related to REST endpoints.

**Comment by anzdaddy** [comment]
This is as intended. The `appname` field represents a reference to the app that contains the referenced type. The `path` field represents the type itself. It's a path because Sysl supports nested types.

**Comment by anzdaddy** [comment]
Apologies, I misread the output. It currently puts `HelloRequest` in the `appname` field. It should be in the `path` field.

**Comment by andrewemeryanz** [comment]
To summarise the issue, consider the following sysl:
```
Foo:
    Endpoint(f1 <: Foo.FooType, f2 <: FooType):
        ...
    !type FooType:
        ...
```

The `sysl.proto` representation of `Endpoint` parameters is:
```
"name":"f1","type":{"typeRef":{"ref":{"appname":{"part":["Foo"]},"path":["FooType"]}}}  # correct
"name":"f2","type":{"typeRef":{"ref":{"appname":{"part":["FooType"]}}}}                 # incorrect 
```

The correct value for `f2` should be:
```
"name":"f2","type":{"typeRef":{"ref":{"appname":{"part":[]},"path":["FooType"]}}}
```

**Comment by ericzhang6222** [comment]
@andrewemeryanz 
Does it need to set current appName as default appName if it is absent? So the correct value for `f2` should be:
```
"name":"f2","type":{"typeRef":{"ref":{"appname":{"part":[Foo]},"path":["FooType"]}}}
```

**Comment by anzdaddy** [comment]
Ultimately, yes, but where this should happen is less clear. I generally prefer the raw parse output to only say what the syntax said, so appname should be empty. But, for the benefit of downstream consumers, it's helpful to resolve the implied appname as above at some point along the processing path. I'm happy for this to happen either immediately or as a post-processing step, which can even be in arr.ai rather than Sysl.

**Comment by anzdaddy** [comment]
Fixed in https://github.com/anz-bank/sysl/releases/tag/v0.221.0
