### ISSUE TITLE
Windows sysl exe throws error while generating diagrams

### ISSUE THREAD

**Issue by sahejsingh** [anz-bank/sysl#105]
### Expected behaviour
SYSL exe should create diagrams in expected location
### Actual behaviour
Throws the following error:
```
=== Cannot remove db: c:\users\singhs93\appdata\local\temp\tmpk2uqdd\.sysl.state.db
'module' object has no attribute 'HTTPSConnection'

```
### Steps to reproduce the behaviour

Run the following command in the `demo/bank` folder

```
sysl --root . sd -o "out/sd-%(epname).png" /project -a "Bank :: Sequences" -v
```

Please note:  The a new temp folder is created everytime you run the above command.

**Comment by blair-bryant** [comment]
I get the same error.

**Comment by juliaogris** [comment]
We should probably add tests with the exes on windows ci

**Comment by sahejsingh** [comment]
Tried the same on a different computer. I got a PNG file which seems corrupted. I did see the error mentioned above.
