### ISSUE TITLE
Update README to clarify installing Sysl using python

### ISSUE THREAD

**Issue by ghost** [anz-bank/sysl#156]
Run following command to install Sysl on Mac
`$ pip install sysl`

### Expected behaviour
Install Sysl successfully

### Actual behaviour
```
$ pip install sysl
Requirement already satisfied: sysl in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sysl-0.2.0-py2.7.egg
Collecting httplib2 (from sysl)

Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection
broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at
0x110259d50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or
not known',)': /simple/httplib2/

Could not find a version that satisfies the requirement httplib2 (from sysl) (from versions: )
No matching distribution found for httplib2 (from sysl)`
```
### Steps to reproduce the behaviour
Run `$ pip install sysl` on Mac terminal

**Comment by juliaogris** [comment]
I have just run this command with `Python 2.7.15` on `macOS 10.13.5` without any problems.

I suspect your issues results from running the command on a corporate network.
The [environment guide](https://github.com/anz-bank/sysl/blob/master/docs/environment_guide.md) (linked from the README at the bottom of the [Development section](https://github.com/anz-bank/sysl#development)) might hold the solution.
