### ISSUE TITLE
go sysl sd produces empty png file.

### ISSUE THREAD

**Issue by sahejsingh** [anz-bank/sysl#232]
### Steps to reproduce the behaviour
cd to  repo, `sysl/docs/assets` directory:

Python sysl sd command produces the correct output:
`sysl sd -s 'MobileApp <- Login' -o call.png call`

But the equivalent go-sysl-sd command:

`sd -endpoint 'MobileApp <- Login' -output call.png -modules call.sysl`

produces an empty file `call.png`.

### Expected behaviour
The above mentioned command should generate the correct sequence diagram

Another issue:
The python and go versions do not have the same command line options.

**Comment by loki5265** [comment]
@sahejsingh I try to simulate your case and can generate the correct result. Check it below:
![call](https://user-images.githubusercontent.com/44768594/59257002-b3593980-8c67-11e9-82b7-77a191c90faf.png)

Could you kindly check if you've started your plantuml server? If not, it would generate an empty png file.

**Comment by sahejsingh** [comment]
plantuml is running at http://localhost:8080/plantuml/

**Comment by sahejsingh** [comment]
are you expecting SYSL_PLANTUML to be set?

**Comment by loki5265** [comment]
@sahejsingh  Yep, it should be.

**Comment by sahejsingh** [comment]
Nope. It should not be. Please check the default behaviour in python version.

**Comment by loki5265** [comment]
@sahejsingh I find the root cause. We've missed the default value for SYSL_PLANTUML. will fix it.
