### ISSUE TITLE
Go SYSL SD cmd: remove -modules arg 

### ISSUE THREAD

**Issue by sahejsingh** [anz-bank/sysl#233]
Following command line args are incompatible with python sysl sd.

- -endpoint instead of -s
- -module instead of the last arg in the commandline
- -o does not work. Have to specify -output.
- --appfmt

### Expected behaviour
The command line options are not compatible with the python version of sysl.
Following command should work:
`sd -s 'MobileApp <- Login' -output call.png  call.sysl`

**Comment by jecofang01** [comment]
Seems like this issue can be closed as it already be fixed in the PR #234
