### ISSUE TITLE
Idea: python exporters and importers should be able to consume protobufs generated by go sysl

### ISSUE THREAD

**Issue by sahejsingh** [anz-bank/sysl#237]
GO SYSL's grammar is not the same as that of python sysl.

To make existing python utilities work with new go sysl, one idea can be to change the python sysl loader module to invoke the go sysl binary's pb command, load the protobufs and return to python utilities.

Swagger exporter could benefit from this approach.

**Comment by cuminandpaprika** [comment]
Closing this as it seems no longer relevant to the current Go implementation of Sysl
