### ISSUE TITLE
Provide support for Enums

### ISSUE THREAD

**Issue by sahejsingh** [anz-bank/sysl#243]
Define enum syntax  to handle the following cases:

- [x] Define Int enum type
- [ ] Define String enum type
- [ ] Add support in codegen

**Comment by camh-anz** [comment]
The AST only supports int enums: https://github.com/anz-bank/sysl/blob/9642e6fe6029546eb17f18aebaa6a473ceb2679c/pkg/sysl/sysl.proto#L246

**Comment by ChloePlanet** [comment]
Fixed.

**Comment by camh-anz** [comment]
Still to be done: String enums.
