### ISSUE TITLE
Move ValueUtil into a package

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/sysl#274]
`syslutil` seems apropos.

**Comment by kasunfdo** [comment]
ValueUtil is used mainly by expression evaluators. Therefore, I think moving all of them into a different package would make more sense. Then following 9 files will be moved to `eval` package. 
@anzdaddy, what is your opinion?

- binexprEval.go
- exprEval.go
- exprEval_test.go
- exprOp.go
- goFuncs.go
- unaryEval.go
- valueType.go
- ValueUtil.go
- ValueUtil_test.go

**Comment by anzdaddy** [comment]
Sounds good. Best to wait for #282 to land in master.

**Comment by kasunfdo** [comment]
In #282, code coverage drops if ValueUtil is moved into syslutil as most of the tests were done by eval tests. As the result, merging blocks. That's why I moved all above files into a single package.
