### ISSUE TITLE
go-sysl: add support for data diagrams

### ISSUE THREAD

**Issue by sahejsingh** [anz-bank/sysl#279]
Add support for sysl data diagrams

See [sysl-data.sysl](https://github.com/anz-bank/sysl/blob/master/demo/simple/sysl-data.sysl)

Expected output:

![sysl-data](https://user-images.githubusercontent.com/31713463/62680267-2b3ea880-b9fa-11e9-8dec-56f01d684631.png)

Types of data diagrams:
- [x] Tuple
- [x] Relational

**Comment by springwiz** [comment]
Taken care in PR #305
