### ISSUE TITLE
Inject rich context info into binaries

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/sysl#299]
#292 adds version info to the sysl binary. Would be good to also track:
- git commit id
- git branch.
- build timestamp (`-ldflags "-X main.BuildTimestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"`).
- $GOOS, $GOARCH and Go version

Not sure if this is easy, or even possible, but the following output would be ideal:

```bash
$ sysl --version
1.2
$ sysl --version -v
sysl version 1.2
git master 7537f593757c20372ab9144cf7ac8fcc23528f17
built 2019-08-26T21:04:34Z
go version go1.12.9 darwin/amd64
```

Other info that caught my attention at https://docs.travis-ci.com/user/environment-variables/:

- TRAVIS_BUILD_NUMBER
- TRAVIS_DIST
- TRAVIS_OS_NAME
- TRAVIS_OSX_IMAGE

**Comment by kasunfdo** [comment]
As it shows information of binary, I think `sysl --info` or `sysl info` would be better.
