### ISSUE TITLE
Inject all relevant git refs into binary

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/sysl#338]
#308 injects the git commit id. Expand this to also list any branches or tags that are of relevance. At bare minimum, any tags on the exact commit should appear.

Suggested output format:

```bash
$ sysl info
⋮
Git refs   : commit:aa7192a05ef6a0b64e588c9a90d632d8b56ef949
             branch:feature/report-git-refs
             tag:experiments/123
```

Note that the version number should be reported separately. Whether it's also included here is an open question.

**Comment by ChloePlanet** [comment]
Fixed.
