### ISSUE TITLE
sd endpoint is a required argument

### ISSUE THREAD

**Issue by jeedo** [anz-bank/sysl#36]
### Expected behaviour
Produce a sequence diagram using the demo bank model by just providing the application

### Actual behaviour
Error and stack trace when command line parsing gets to endpoints

### Steps to reproduce the behaviour
```
PS C:\dev\sysl> sysl sd --app ATM --plantuml http://localhost:8080/plantuml /demo/bank/bank -o out\atm.txt
Traceback (most recent call last):
  File "C:\tools\winpython\2.7.12.4\python-2.7.12.amd64\Scripts\sysl-script.py", line 11, in <module>
    load_entry_point('sysl==0.1.1', 'console_scripts', 'sysl')()
  File "C:\tools\winpython\2.7.12.4\python-2.7.12.amd64\lib\site-packages\sysl\core\__main__.py", line 125, in main
    args.func(args)
  File "C:\tools\winpython\2.7.12.4\python-2.7.12.amd64\lib\site-packages\sysl\core\syslseqs.py", line 470, in cmd
    endpoints=[i[0] for i in args.endpoint],
TypeError: 'NoneType' object is not iterable
```

**Comment by juliaogris** [comment]
G'day @jeedo and thanks for reporting this issue! 
We will look into it and try our best to have a fix or at least a workaround as soon as possilbe.

**Comment by jeedo** [comment]
A bit of reverse engineering the command line args and managed to get some sensible output from

```
sysl --root demo/bank sd --app "Bank :: Sequences"  --plantuml http://localhost:8080/plantuml  -o out\%(epname).svg //project
```

**Comment by juliaogris** [comment]
Great to hear that you found a workaround! Feel free to add feature suggestions etc. to this issue tracker as well.  
 
From your console output I can see you work on Windows. We intend to release a standalone `sysl.exe` for Windows soon in case this helps your cause.
  
I'll keep you posted when we have a fix for the initial issue.

**Comment by juliaogris** [comment]
@jeedo we have got a PR #38 in the works to fix this issue with a more meaningful error messages.

As you have correctly noted, you have to use `sysl sd` with one of
- output pattern `%(epname)`, e.g. `-o "out/%(epname).svg"`
- specific endpoint e.g. `--endpoint "ATM <- GetBalance"`
