### ISSUE TITLE
Better XSD import handling

### ISSUE THREAD

**Issue by anz-gordonj7** [anz-bank/sysl#369]
A warning would help that the maxOccurs is not a number in the XSD.

_Originally posted by @springwiz in https://github.com/anz-bank/sysl/pull/361_

**Comment by ericzhang6222** [comment]
@anz-gordonj7 I can't make sure your point. Can you help to confirm my understanding?
Now the code line 17, 18 in xsd.go will raise error if maxOccurs in not a number in XSD,
`specs, err := xsd.Parse([]byte(text))
	if err != nil {
		return "", err
	}`
and the error is
`ERRO[0000] Error at complexType(account)>complexContent: strconv.Atoi: parsing "n": invalid syntax`. 
So you want to make this error more clear and meaningful as now it is pretty simple? Like this format:
`ERRO[0000] maxOccurs is not a number in XSD line 18`?

**Comment by anz-gordonj7** [comment]
Yes, the error that gets reported now is not user friendly. The error message should say something like "the value X is not a number, maxOccurs requires a number. Aborting"

**Comment by ericzhang6222** [comment]
@anz-gordonj7, I checked code and I preferred approach is updating code in vendor/aqwari.net/xml, it is easy and effective. The risk is not sure if the code will be removed or replaced by some other framework in the future. What is your thoughts?

**Comment by ericzhang6222** [comment]
> @anz-gordonj7, I checked code and I preferred approach is updating code in vendor/aqwari.net/xml, it is easy and effective. The risk is not sure if the code will be removed or replaced by some other framework in the future. What is your thoughts?

@anz-gordonj7, I tried golang reflect, but it couldn't work as the struct is:
`type parseError struct {
	message string
	path    []*xmltree.Element
}`
struct and its property access modifier is not public and can't get property's value in other package. So it will raise error 'panic: reflect.Value.Interface: cannot return value obtained from unexported field or method'.

And, another way is check xml content and find its tag(maxOccurs) via its value in error message, but it is not good.

**Comment by ericzhang6222** [comment]
Discussed with @anz-gordonj7 , we agreed to close this issue and current XML process vendor has provided error message like 'ERRO[0000] Error at complexType(account)>complexContent: strconv.Atoi: parsing "n":', and it is not a job of sysl to make specific error message is more friendly.
