### ISSUE TITLE
Need validation before unmarshall response in restlib

### ISSUE THREAD

**Issue by JackLeeHal** [anz-bank/sysl#407]
When we generate a client file in golang with two expected kinds of response it will generate code like `responses := []interface{}{&A{}, &B{}}`
This response will pass into `restlib.DoHTTPRequest()`
In this method's

```go
for _, respInterface := range response {
	err = json.Unmarshal(respBody, respInterface)
	if err == nil {
		return makeHTTPResult(httpResponse, respBody, respInterface), nil
	}
} 
```

It didn't do the validation before `unmarshall`, so this `unmarshall` method never failed, it always marshall the `respBody` to the first `respInterface` come up from the for loop.
In this case, the response body will always return as &A{}.

**Comment by JackLeeHal** [comment]
Issue happened here: https://github.com/anz-bank/syslgen-examples/blob/master/restlib/restlib.go#L74-L79
https://play.golang.org/p/vJ46sZ-VqKh  What I did in this example is just like the restlib unmarshal the response body.
And this example shows how Human unmarshal to Car!

Propose to use https://godoc.org/gopkg.in/go-playground/validator.v10(Just know they got v10, we still use v9 in gobff)to validate json struct before unmarshal.
This may need changes for both restlib(add validation logic) and the transform file(add validation tag) we use.

**Comment by anzdaddy** [comment]
The longer term solution is for the generated code to derive the type of the response from the response code. @gkanz and I have discussed this before and come up with a strategy, which is why I assigned it to him (so he can elaborate the solution here, possibly for someone else to work on).

**Comment by gkanz** [comment]
Agree, the unmarshall needs to be fixed. This is a restlib issue, tenerated code does cast assertions to check which type is returned.

**Comment by anzdaddy** [comment]
Random musings: Since Sysl (and Swagger, I think) maps status codes to return types, the following concept provides a very flexible way to access results based on either status codes or return types. The case in point is overkill (done that way for illustrative purposes) since there is only one return type and one error type. In practice, if there's a single type, the codegen could simply return the given types directly without the type-casting machinery.

#### Generated code

```go

func FooBar(ctx context.Context, arg1 string) (FooBarResult, error) { … }

type FooBarResult interface{}

type FooBarResultStatusOK interface {
	CustomerProfile() *CustomerProfile
}

type FooBarErrorStatusBadRequest interface {
	ErrorInfo() *ErrorInfo
}

type FooBarErrorStatusUnauthorized interface {
	ErrorInfo() *ErrorInfo
}

type FooBarResultTypeCustomerProfile struct {
	result *CustomerProfile
}

func (r *FooBarResultTypeCustomerProfile) CustomerProfile() *CustomerProfile {
	return r.result
}

type FooBarErrorTypeErrorInfo struct {
	result *ErrorInfo
}

func (r *FooBarErrorTypeErrorInfo) ErrorInfo() *ErrorInfo {
	return r.result
}
```

#### Developer code

```go
func foo() {
	r, err := FooBar(...)
	if err != nil {
		switch r := r.(type) {
		case FooBarErrorStatusBadRequest:
			panic("wat?")
		case *FooBarErrorTypeErrorInfo:
			fmt.Error(r.ErrorInfo())
		}
	}
	switch r := r.(type) {
	case FooBarResultStatusOK:
		doSomethingWith(r.CustomerProfile())
	}
}
```

**Comment by gkanz** [comment]
This is also a bit messier than it initially looks as I have not seen any Swagger or SYSL that fully specifies all the return types. I have seen some shorthand in Swagger that specifies different types against 2XX, 4XX and 5XX. It would be good to not have to specify every possible status.

Returning multiple types also lends itself to a switch btw:
```go
switch {
  case customerProfile != nil:
    doSomethingWith(customerProfile)
  case errorInfo != nil:
    fmt.Error(errorInfo)
  case err != nil:
    panic(err.Error())
}
```
and the status can be passed back in the context if someone really wants to know what it was.
