### ISSUE TITLE
Need Camel-Case in request param generated

### ISSUE THREAD

**Issue by JackLeeHal** [anz-bank/sysl#408]
This is just a minor issue

When we generated the client code in golang.
The params in request is always in lower case even if it's Camel-Case in Sysl file. E.g., `firstName` becomes `firstname`.
I guess this is not happened in Sysl -> AST.
Most likely in AST + transform -> code.(There are lot of `ToLower()` in that transform)

**Comment by anzdaddy** [comment]
The intent is to follow Go coding conventions. Can you point to a specific case you think is doing the wrong thing?

**Comment by anzdaddy** [comment]
Is the problem that `fooBar` is becoming `foobar`? If so, then that should definitely be fixed.

**Comment by Joshcarp** [comment]
@JackLeeHal Any specific examples?

**Comment by Joshcarp** [comment]
@JackLeeHal as far as I can tell this has got to do with the transform code you're using. 
If you could give any examples that'd help a lot
