### ISSUE TITLE
Update go openapi importer to match Python importer

### ISSUE THREAD

**Issue by gkanz** [anz-bank/sysl#434]
### Expected behaviour
Go importer handles query params consistently with Python importer.
Go importer handles multiple return types consistently with Python importer.

### Steps to reproduce the behaviour
Import the same OpenAPI spec with both Go and Python, the results will be different in certain aspects.

**Comment by anz-gordonj7** [comment]
Implementing openapi-3.0 importing at the same time.

**Comment by anz-gordonj7** [comment]
Done
