### ISSUE TITLE
Fix datetime parsing bug

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/sysl#443]

**Comment by rizwan-rehman** [comment]
Hey Marcelo,
Please find below the steps to reproduce the issue:

- Retrieve the order from PO Database.
- Individual entity has the DOB as below:

`"Individual": [
    {
      "customerId": 1,
      **"dateOfBirth": "1979-01-20",**
      "firstName": "Steve",
      "gender": "U",
      "lastName": "Erwin",
      "middleName": "Mia",
      "title": "Mx"
    }
  ],`

- On json.Unmarshal() call SYSL is returning following error:
`parsing time ""1979-01-20"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "T"`
 
Find below the sample Go code:
`po := sysl.NewPoOrder()
 err := json.Unmarshal(poResp, &po)
`
Find below the sample PO JSON Data:

`{
		"Address": [
		  {
			"addressId": 6,
			"customerId": 1,
			"addressType": "CRES",
			"city": "Greensborough",
			"country": "AU",
			"postcode": "3088",
			"state": "VIC",
			"streetName": "Selsdon",
			"streetNumber": "12",
			"streetType": "Court"
		  },
		  {
			"addressId": 7,
			"customerId": 1,
			"orderItemId": 3,
			"addressType": "STMT",
			"city": "Greensborough",
			"country": "AU",
			"postcode": "3088",
			"state": "VIC",
			"streetName": "Selsdon",
			"streetNumber": "12",
			"streetType": "Court"
		  },
		  {
			"addressId": 8,
			"customerId": 1,
			"addressType": "CMAL",
			"city": "Greensborough",
			"country": "AU",
			"postcode": "3088",
			"state": "VIC",
			"streetName": "Selsdon",
			"streetNumber": "12",
			"streetType": "Court"
		  }
		],
		"AppCustRelationship": [
		  {
			"customerId": 1,
			"applicationId": 2,
			"relationshipType": "POW"
		  }
		],
		"Application": [
		  {
			"applicationId": 2,
			"applicationSigned": false,
			"applicationSource": "SOLA",
			"applicationSourceCode": "QMV",
			"applicationSourceCountry": "AU",
			"applicationVersion": 1,
			"basketId": 5284,
			"bsb": "013265",
			"channel": "I",
			"createdDate": "2020-03-16T13:34:05.311+11:00",
			"currencyCode": "AUD",
			"modifiedBy": "Apply User",
			"orderId": 1000005389
		  }
		],
		"CardRequest": [
		  {
			"customerId": 1,
			"orderItemId": 3,
			"accessLevel": "Full",
			"cardDesign": "blue",
			"cardLinkageNumber": 2,
			"cardRequestId": 10,
			"cardSequenceId": 1,
			"cardType": "ANZAccessVisaDebit",
			"contactlessBehaviour": "Tap and PIN",
			"dispatchMethod": "Mail",
			"fastBalance": true,
			"fastCash": true
		  }
		],
		"Contact": [
		  {
			"contactId": 5,
			"customerId": 1,
			"contactType": "E",
			"email": "abhijit.khan@corptst.anz.com"
		  },
		  {
			"contactId": 9,
			"customerId": 1,
			"contactNumber": "0429002580",
			"contactType": "M"
		  }
		],
		"CustOrderItemRelationship": [
		  {
			"customerId": 1,
			"orderItemId": 3,
			"custAcctRelationship": "SOL",
			"orderItemFlag": "N"
		  }
		],
		"Customer": [
		  {
			"customerId": 1,
			"acceptMarketing": true,
			"customerType": "IND",
			"depositCustomerType": "STD",
			"existingCustomer": false,
			"fullName": "Steve Mia Erwin",
			"privacyConsent": true,
			"selfCertificationIndicator": "A",
			"verificationStatus": "Verified"
		  }
		],
		"Declaration": [
		  {
			"declarationID": 4,
			"applicationId": 2,
			"customerId": 1,
			"declarationItem": "I request that ANZ issue me with a Visa Debit card to access my Access Advantage account."
		  }
		],
		"Deposit": [
		  {
			"orderItemId": 3,
			"ATOType": "I",
			"numberOfSignatories": 1,
			"transactionAccountType": "IND"
		  }
		],
		"Individual": [
		  {
			"customerId": 1,
			"dateOfBirth": "1979-01-20",
			"firstName": "Steve",
			"gender": "U",
			"lastName": "Erwin",
			"middleName": "Mia",
			"title": "Mx"
		  }
		],
		"OrderItem": [
		  {
			"orderItemId": 3,
			"capProductCode": "DDA",
			"capSubProductCode": "PT",
			"eStatementEmail": "abhijit.khan@corptst.anz.com"
		  }
		]
	  }`

**Comment by rizwan-rehman** [comment]
Unmarshal on Date fields are not working. Find below the Steps:

1). Create a date with format "YYYY-MM-DD" e.g. "1979-01-20"
2). Unmarshal the date will give the following error:

parsing time ""1979-01-20"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "T"

**Comment by anzdaddy** [comment]
Implemented, but the target code base uses Go 1.12, which doesn't compile at present. I'll investigate to discern the cause and decide the best course of action.

**Comment by anzdaddy** [comment]
Fixed
