### ISSUE TITLE
Make sysl playground

### ISSUE THREAD

**Issue by Joshcarp** [anz-bank/sysl#470]
explore viability of a client side playground based on 

gopherjs.github.io
(github.com/gopherjs/gopherjs.github.io)

or if not possible, see how to go about implementing from 
play.golang.org
github.com/golang/playground

**Comment by anz-gordonj7** [comment]
Haha, interesting. Need to get the repl/debugger complete and then this can get closer to being viable. I don't think this should be very high priority though.
