### ISSUE TITLE
Alias bug

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#473]
It seems like data model diagrams don't get created correctly when the !alias keyword is used:
Using:
```
Project:
    _:
        App
App:
    !type User:
        id <: uuid
        acc <: Account
    !type Account:
        foo <: string
    !alias uuid:
        int
```
![project](https://user-images.githubusercontent.com/32605850/70760005-5f591a00-1d9c-11ea-9ea9-d71533883c64.png)

## Expected behaviour:
The undefined note `_1` should be an alias type, rendering a graph like this:

![project](https://user-images.githubusercontent.com/32605850/70761386-27080a80-1da1-11ea-9f24-83891957d23b.png)

**Comment by ericzhang6222** [comment]
Another sample!
sysl expression:
Project:
    _:
        App
        
App:
    !alias Orders:
         sequence of ints
    !type Foo:
        order_id <: Orders

Expected Diagram:
![Expected](https://user-images.githubusercontent.com/59079351/72311358-515e2800-36bf-11ea-8d19-03224cbeb4b5.png)

Actual Diagram:
/Users/ezhang/Projects/ANZx/sysl/defects/project.png

**Comment by ericzhang6222** [comment]
@joshcarp, it has been fixed in branch master, can you help to verify? Thanks.
