### ISSUE TITLE
Data Diagrams don't render multiple applications in a project

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#474]
Given the code: 

```
Project:
    _:
        Server
        App

Server:
    !type id:
        id <: int
App:
    !type User:
        id <: Server.id
        
```
And running the command `sysl data -o project.png -j Project project.sysl`
Both `server` and `app` should be rendered, although only the last declared in `Project` is
![project](https://user-images.githubusercontent.com/32605850/70770127-45313300-1dc0-11ea-947e-10e2fb5267f1.png)
This Diagram should have both `Server.id` and `App.User`

**Comment by nofun97** [comment]
https://github.com/anz-bank/sysl/blob/master/cmd/sysl/cmd_datamodel.go#L14-L71 this part seems strange because it would iterate through the applications and generate a raw plantuml for each application and then it would store the raw plantuml at `outmap[outDir]` so it replaces the processed value everytime it finishes processing

**Comment by springwiz** [comment]
The correct usage of the tool as far as I remember was:
sysl data -o  "%(epname).png" -j Project data.sysl
"%(epname).png" means include all the applications in the output.

**Comment by nofun97** [comment]
> The correct usage of the tool as far as I remember was:
> sysl data -o "%(epname).png" -j Project data.sysl
> "%(epname).png" means include all the applications in the output.

tried `sysl data -j Project data.sysl` with the sysl module above, since output defaults to `%(epname).png`. It still produces the same diagram

**Comment by nofun97** [comment]
I discussed with @springwiz and relationships between applications are not to be represented in a data diagram, data diagram is supposed to describe relationship between tables, so by current design what @Joshcarp is doing isn't a proper use

**Comment by ericzhang6222** [comment]
hi @Joshcarp, can you provide an expected diagram like https://github.com/anz-bank/sysl/issues/473? It will be very helpful, thanks.

**Comment by Joshcarp** [comment]
It should be something like this: http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhEIImkLWWjJYrIu5A0qBgwTWgUALmGAI2h6YYHcQAGcLV2LSlba9gN0jG70000

**Comment by ericzhang6222** [comment]
@Joshcarp, is following picture expected result?
![474_Expected](https://user-images.githubusercontent.com/59079351/72336223-4cb76500-36fb-11ea-8e1b-2f3a878799e1.png)

**Comment by ericzhang6222** [comment]
Set it as low priority as discussed. @Joshcarp @anzdaddy @springwiz

**Comment by anzdaddy** [comment]
This appears to be a blocker for architects. Let's reexamine.

**Comment by anzdaddy** [comment]
obsolete
