### ISSUE TITLE
Codegen generate wrong go code - Redundant semicolon

### ISSUE THREAD

**Issue by ChloePlanet** [anz-bank/sysl#475]
The command: `sysl codegen --grammar=unsorted/examples/grammars/go/go.gen.g --transform=unsorted/examples/grammars/go/go.gen.sysl demo/simple/hello --start goFile`

### Expected behaviour
```go
package helloworld

//Message ...
 type Message struct {
 	 Text string `json:"text"`
 }
```

### Actual behaviour
There's a semicolon at the end of package line: `package helloworld ;`

**Comment by anzdaddy** [comment]
Code generators should run a reformatter (gofmt, goimports or the like) as the last stage. It looks like this might not be happening in this instance.

**Comment by ericzhang6222** [comment]
It is caused by 'PackageClause: 'package' PackageName '\n';' in go.gen.g, fixed this issue with https://github.com/anz-bank/sysl/pull/505.

**Comment by ericzhang6222** [comment]
Hi @ChloePlanet, this issue has been fixed, can you help to verify with code in branch master and close? Thanks.
