### ISSUE TITLE
CI Caching

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#481]
It seems like the ci caches the go test results, which means that if a non go file is changed (see #480) The CI will pass for everything except windows build. 

A fix might be to use `go test ./... -count=1` for CI scripts

**Comment by anzdaddy** [comment]
Caching passing tests is a good thing. Let's think carefully before suppressing it. In general, I'm not a fan of golden-file testing. I would prefer to see the content baked into the tests themselves.

If we want to retain the convenience of managing large files (with syntax highlight in editors, etc.), we can have our cake and eat it too by code-generating a go package that exposes a directory of files as an in-memory `http.FileSystem` (for which [tooling already exists](https://github.com/avelino/awesome-go#resource-embedding)). This can then be wrapped in an `afero.Fs`.

**Comment by ChloePlanet** [comment]
Fixed.
