### ISSUE TITLE
importing query params with hyphens generate bad sysl

### ISSUE THREAD

**Issue by suipinglu** [anz-bank/sysl#499]
Attempting to import a swagger/openAPI spec where a query parameter contains a '-' causes the generated sysl to contain the - also, which is invalid.

example:
```
- name: cust-nums
     type: string
     required: true
     in: query
```

generated out to `?cust-nums=string&....` The python importer would convert that to `custNums=string` which is now valid sysl but no longer follows the spec.

**Comment by anz-gordonj7** [comment]
There is not enough information here to do anything about.
1) We need to see at least the relevant snippet from the input file
2) the importer understands 4 different input types, which are you using?

**Comment by suipinglu** [comment]
The one i use is converting swagger from yaml into sysl. source file are sensitive, so can not post in here.

**Comment by anz-gordonj7** [comment]
You need to then create a small yaml snippet with just the broken bits that isnt sensitive, or ping me on slack

**Comment by anz-gordonj7** [comment]
@gkanz @anzdaddy The importer generates this for header and body fields with hyphens/unsafe names: `x_b3_traceid <: string [~header, ~required, name="X-B3-TraceId"]` Could we add the same for query params (using ~query attribute) and drop it from the query line in the sysl? This would need some changes to the codegen presumably to work but would more closely reflect the spec.

**Comment by anzdaddy** [comment]
I'm not totally averse, but there are some points to consider:

1. Alignment to the Swagger model isn't a goal.
2. The current syntax was intended for succinctness and to visually match what the URL line looks like. We should be very cautious before sacrificing this.
3. The ultimate goal is clarity of expression, so if there's a consensus that moving query parameters to a separate line each will improve this. I'm all for it.
4. Some real world examples would help.
