### ISSUE TITLE
output raw plantuml

### ISSUE THREAD

**Issue by nofun97** [anz-bank/sysl#503]
related to #501 and #474.

we should add a way to output the raw plantuml for debugging (proposed by @anzdaddy)

**Comment by nofun97** [comment]
whoops nevermind, to output raw uml you can set the output filename to have `.uml` extension. The generated raw plantuml is still wrong, will close this issue and investigate further.

**Comment by anzdaddy** [comment]
Hehe. I'd forgotten about that.
