### ISSUE TITLE
swagger/openAPI does not handle remote file references

### ISSUE THREAD

**Issue by anz-gordonj7** [anz-bank/sysl#509]
swagger allows $ref to refer to an object in another swagger file (see https://swagger.io/docs/specification/using-ref/)

This is currently not supported by the sysl importer

**Comment by nofun97** [comment]
just to clarify, in additional to adding the definitions in the same file, there will be an additional feature to add local files (url links not included for now)

**Comment by marcelocantos** [comment]
What's the priority on this? Is there a real-world scenario blocking us right now?

**Comment by nofun97** [comment]
i discussed this briefly yesterday, i think @anz-gordonj7 mentioned it's not urgent but it would be a great feature to have

**Comment by anz-gordonj7** [comment]
Request from dcx bff people I can take it over if you'd prefer but I tihnk Novan has it almost finished?
