### ISSUE TITLE
sysl-modules: `go get` with specific GOPATH

### ISSUE THREAD

**Issue by ChloePlanet** [anz-bank/sysl#512]
Considering download go modules to specified path as mentioned in #500 . i.e the `.sysl/` directory if found, or the `SYSLPATH` envvar.

**Comment by anzdaddy** [comment]
GOPATH is [deprecated since Go 1.13](https://blog.golang.org/modules2019#TOC_2.), so let's think carefully about whether it makes sense to mirror the concept Sysl.
