### ISSUE TITLE
codegen does not wireup properly when url involved with underscore

### ISSUE THREAD

**Issue by suipinglu** [anz-bank/sysl#513]
issues with codgen from sysl file to generate go code. When **downstream url got underscore**, go code does not wire up properly.

perhaps the issue is under svc_interface.sysl, not sure here.

this is the source snippet from the sysl file for downstream:

```
    /tnt/verification-service-api:
        /verifications/addresses/cannonical_address/{id<:string}:
            GET:
                | No description.
                return error <: Error
                return ok <: Address
```

client downstream types.go got these:
```
// GetTntVerificationServiceApiVerificationsAddressesCannonical_addressRequest ...
type GetTntVerificationServiceApiVerificationsAddressesCannonical_addressRequest struct {
	Id string
}
```
upstream define and wire up with the following:
```
        /qas/detailed-address/{qasId<:string}:
            GET:
                Qas <- GET /tnt/verification-service-api/verifications/addresses/cannonical_address/{id<:string} 
```

### Actual behaviour

```
// GetV1BffQasDetailedAddress Client => DID NOT WIRE UP CORRECTLY HERE
type GetV1BffQasDetailedAddressClient struct {
}
```
### Expected behaviour
```
// GetV1BffQasDetailedAddress Client
type GetV1BffQasDetailedAddressClient struct {
	GetTntVerificationServiceApiVerificationsAddressesCannonicalAddress func(ctx context.Context, req *qas.GetTntVerificationServiceApiVerificationsAddressesCannonical_addressRequest) (*qas.Address, error)
}
```

**Comment by marcelocantos** [comment]
Underscores should collapse during codegen, so in the expected behaviour above, this:
```
GetTntVerificationServiceApiVerificationsAddressesCannonical_addressRequest
```
...should be this:
```
GetTntVerificationServiceApiVerificationsAddressesCannonicalAddressRequest
```

**Comment by uynap** [comment]
I tested it last night. codegen works fine for me.

**Comment by suipinglu** [comment]
i think there is two issues at one goal here:
1. the codegen should do a better camelCase, no doubt. This is a go convention good practices.
2. the interface go file need to wire up properly:
```
type GetV1BffQasDetailedAddressClient struct {
// expected something to be here other than empty
}
```

**Comment by suipinglu** [comment]
> I tested it last night. codegen works fine for me.
> 
> Ok. When I say "works fine", it's the codegen creates function names contains underscores if there's an underscore in the endpoint.

it creates all the functions for me as well, but only the interface part is missing.

**Comment by uynap** [comment]
Sorry, when I say "functions", I actually means it creates everything for me and I also try to run the BFF, the endpoint contains underscore is working.

**Comment by suipinglu** [comment]
> i think there is two issues at one goal here:
> 
> 1. the codegen should do a better camelCase, no doubt. This is a go convention good practices.
> 2. the interface go file need to wire up properly:
> 
> ```
> type GetV1BffQasDetailedAddressClient struct {
> // expected something to be here other than empty
> }
> ```

i figure it out. there is a sysl syntax issue in here:
```
 /qas/detailed-address/{qasId<:string}:
            GET:
                Qas <- GET /tnt/verification-service-api/verifications/addresses/cannonical_address/{id<:string} 
```
and it has to be like this without the "<:string" while defining the downstream in server sysl:
```
 /qas/detailed-address/{qasId<:string}:
            GET:
                Qas <- GET /tnt/verification-service-api/verifications/addresses/cannonical_address/{id} 
```
 
Perhaps we need more completed examples on [sysl docs](https://sysl.io/docs/)? 

@ashwinsajiv, Marcelo's camel case still valid, but at least it is not blocking me to move forward now.

Cheers,
Ping

**Comment by ashwinsajiv** [comment]
Alright! Will have a look into the camel case issue.

**Comment by marcelocantos** [comment]
We should relax the constraints on how to express a call to a REST endpoint. #520

**Comment by ChloePlanet** [comment]
Ping: we handcode the openapi or swagger into sysl for the moment.
