### ISSUE TITLE
It prints error 'ERRO[0000] Get latest git release info error: exit status 128' always when execute sysl binary file

### ISSUE THREAD

**Issue by ericzhang6222** [anz-bank/sysl#559]
Build sysl with latest code in branch master to binary file, and then execute, it will print following logs alway: ERRO[0000] Get latest git release info error: exit status 128 

Is it necessary? I think it is easy to confuse end customer.

**Comment by anzdaddy** [comment]
Not necessary. It should be moved to a debug-level log accessible via a `-v` command line parameter.

**Comment by ChloePlanet** [comment]
This issue is the same as #558.
