### ISSUE TITLE
Move all related code generation to this repo

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#587]
### Current Sysl Version
currently the following is needed to generate code:

`sysl codegen --transform transforms/svc_client.sysl --grammar grammars/go.gen.g --start goFile  -outdir=output --app-name Simple model/1_project.sysl`

These transforms and grammars should be included in this repo and used by default and use `sysl modules`

### Use-cases
This could simplify the command to something like:
`sysl codegen --language=go --app-name Simple model/1_project.sysl`

**Comment by anz-gordonj7** [comment]
I disagree. transforms should not be implicitly built into the sysl repo
