### ISSUE TITLE
Feature: List the environment variables read by sysl

### ISSUE THREAD

**Issue by cuminandpaprika** [anz-bank/sysl#597]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Current Sysl Version

```sh
$ sysl info
...
v0.4.0
```

### Use-cases
To improve the useability of SYSL, the help command should list the environment variables read by sysl.

See below for an example
![image](https://user-images.githubusercontent.com/25007585/74486802-f6179380-4f11-11ea-93a5-6b0066fa7987.png)

**Comment by ChloePlanet** [comment]
I've added a subcommand `sysl env` to show the sysl related envvar.

**Comment by anzdaddy** [comment]
@ChloePlanet is there a related PR you can link?

**Comment by cuminandpaprika** [comment]
Implemented by https://github.com/anz-bank/sysl/pull/554
