### ISSUE TITLE
Support hash map in the type define

### ISSUE THREAD

**Issue by uynap** [anz-bank/sysl#622]
The use case is the frontend requires a hash map in the JSON returned from the backend.
For example, below is the JSON we want to send from backend to the frontend.

```JSON
{
  "data": {
    "a": {"a1": "v1", "a2": "v2"},
    "b": {"a1": "v1", "a2": "v2"},
    ...
  }
}
```

The corresponding Golang code is
```golang
type Response struct {
	Data map[string]Item `json:"data"`
}

type Item struct {
	A1 string `json:"a1"`
	A2 string `json:"a2"`
}
```

Then the supposed Sysl code is
```sysl
!type Response:
    Data <: map[string]Item:
        @json_tag = "data"

!type Item:
    A1 <: string:
        @json_tag = "a1"
    A2 <: string:
        @json_tag = "a2"
```

**Comment by anzdaddy** [comment]
Let's have his:

```sysl
!type Response:
    Data <: set of Item

!type Item:
    name <: string [~pk]
    A1 <: string
    A2 <: string
```

generate something like this:

```go
type Response struct {
	Data ItemSet `json:"data"`
}

type Item struct {
	Name string `json:"name"`
	A1 string `json:"a1"`
	A2 string `json:"a2"`
}

type ItemSet struct {
	m map[string]Item
}

func (s *ItemSet) Add(item *Item) { s.m[item.name] = item }
func (s *ItemSet) Lookup(name string) *Item { return s.m[name] }
…
```

**Comment by uynap** [comment]
This is exactly what I'm looking for.

However, when I use this sysl syntax to run the "sysl gen", I got some issues... 

I also try the latest(master) sysl with latest transform files(codegen files).

**Comment by cuminandpaprika** [comment]
Having a look today, will let you know how I go. Will probably be asking for some assistance from @springwiz

**Comment by springwiz** [comment]
@anzdaddy Do we really need the map in a set, I feel the following could work equally well.
 
// Item ... 
 type Item struct {
 	 A1 string `json:"A1"` 
 	 A2 string `json:"A2"` 
 	 Name string `json:"-"` 
 }

 // Response ... 
 type Response struct {
 	 Data map[string]Item `json:"Data"` 
 }

**Comment by anzdaddy** [comment]
The intent is to offer more than the current requirement. One particular enhancement I have in mind is multiple indices, which will be difficult to introduce later if we go with a map structure now.

**Comment by springwiz** [comment]
Fixed in Server-lib.
