### ISSUE TITLE
Docker image will not run on Docker desktop 

### ISSUE THREAD

**Issue by alecthegeek** [anz-bank/sysl#666]
### Description

When running the Docker image with

```
docker container run --rm anzbank/sysl:latest help`
```

an error occurs

```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

### Steps to Reproduce
1. run the command `docker container run --rm anzbank/sysl:latest help` at the PowerShell of WSL prompt 

**Expected behavior:**

Some nice help text is displayed

**Actual behavior:**
```
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

* Debug&Crash Output

N/A

### Your Environments
>> docker version
Client:
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        2355349d-
 Built:             10/14/2019 16:41:26
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Windows 10 Pro

**Comment by alecthegeek** [comment]
Maybe add the Dockerfile to the repo?

PS -- Link to docker file is broken on your site.

**Comment by camh-anz** [comment]
The `Dockerfile` in the sysl repo (https://github.com/anz-bank/sysl/blob/30eee5c5c4fdc814077541724863e8de2c45e0b3/Dockerfile) simply copies the binary built outside the image into an alpine-based container.

This will not work. The execution environment in github actions is different to that of the deployed alpine image. In particular, the github actions environment seems to be glibc-based, but alpine is musl-based. As such, the `/sysl` binary in the container image links to the wrong dynamic loader:

```
$ docker container run --rm -it --entrypoint /bin/sh anzbank/sysl:latest
/go # ldd /sysl
        /lib64/ld-linux-x86-64.so.2 (0x7fb0571d1000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fb0571d1000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fb0571d1000)
```
That first `/lib64/ld-linux-x86-64.so.2` does not exist, hence the "no such file or directory" error.

To fix this, the `Dockerfile` needs to build sysl inside the container as one normally does with Dockerfiles.

**Comment by alecthegeek** [comment]
I'll submit a PR in the next couple of days
