### ISSUE TITLE
User simplification

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#672]
Certain things with sysl are pretty tedious; 

- The need for @json_tag on every type
- The need to specify `@package` for code generation
- needing `ok <: type` in the return types 

We need either to simplify the syntax, or to have proper error messages/suggestions in the cli tool.

**Comment by joshcarp** [comment]
Also the Validator should work properly

**Comment by ericzhang6222** [comment]
Hi @joshcarp, can you provide some expected outcome samples?

**Comment by gkanz** [comment]
Except for @json_tag, SySL should also tell you that it has defaulted these things. They are there for configurability. As per the discussions on the channel I think behaviour should be clarified before defaults are implemented.

**Comment by ericzhang6222** [comment]
Alexander Eresov is working on @json_tag piece.

**Comment by ericzhang6222** [comment]
Alexander Eresov is working on @json_tag piece.

**Comment by anzdaddy** [comment]
Is there an issue for @json_tag?

**Comment by ericzhang6222** [comment]
> Is there an issue for @json_tag?

There is no issue for @json_tag, Josh want to remove unnecessary @json_tag and make it is simple.

**Comment by ericzhang6222** [comment]
Reopen and Assign to Alexander Eresov as he is working on @json_tag piece.

**Comment by ericzhang6222** [comment]
Following items have been completed:
The need to specify @package for code generation
needing ok <: type in the return types

**Comment by ericzhang6222** [comment]
Item needing ok <: type in the return types has been done in https://github.com/anzx/acceleration/issues/63 from transform Sysl file. And I have reverted code changes in Sysl go code.
