### ISSUE TITLE
Hyperlinks in svg diagrams

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#684]
Having the ability to link to repos/source sysl/anything would be nice within a plantuml diagram. 
An example of this is, taking this example: 

[Simple sysl data model diagram](https://anz-bank.github.io/sysl-playground/?input=UHJvamVjdDoKICAgIFNlcnZlcjoKICAgICAgICBTZXJ2ZXIKICAgIEFwcDoKICAgICAgICBBcHAgCiAgICBSZWxhdGlvbmFsLU1vZGVsOgogICAgICAgIFJlbGF0aW9uc2hpcHMKU2VydmVyOgogICAgIXR5cGUgaWQ6CiAgICAgICAgaWQgPDogaW50CkFwcDoKICAgICF0eXBlIFVzZXI6CiAgICAgICAgaWQgPDogU2VydmVyLmlkCkFub3RoZXJPbmU6CiAgICAhdHlwZSBuYW1lOgogICAgICAgIGZpcnN0TmFtZSA8OiBzdHJpbmcKICAgICAgICBsYXN0TmFtZSA8OiBzdHJpbmcKUmVsYXRpb25zaGlwczoKICAgICF0YWJsZSBBY2NvdW50OgogICAgICAgIFJlc291cmNlSUQgPDogc3RyaW5nIFt+cGtdCiAgICAgICAgQWNjb3VudElEIDw6IHN0cmluZwogICAgIXRhYmxlIFJvbGU6CiAgICAgICAgUm9sZUlEIDw6IGludCBbfnBrXQogICAgICAgIFJvbGVOYW1lIDw6IHN0cmluZwo=&cmd=c3lzbCBkYXRhIC1vICIlKGVwbmFtZSkuc3ZnIiAtaiBQcm9qZWN0IDFfcHJvamVjdC5zeXNs)

Into something that looks like [this](http://www.plantuml.com/plantuml/uml/bL5DImCn4BtdLppteaQxTJqkfRIO889qGTPJAP8cqGssYIIpUX3_km4hWdY8xpYyZpSpYqGgqhZViUDYP2gASA0kx_lkMgxatRAN0bUTa9XC83gikXvItFH7m3zTYy6OtgcKK3s6i5MnWafukC1iXXDn7g8Ud3d5V8vtTWOTF5bFQC6vCvopZs-nCr_2vc-XCsZXFB7rUY1wIUrq-kHe6BUr3dlSElyC2aXXZDfkDZ-sRuCY-seFhIuBMvM6v3LvldFLr7M3AfTdEUBNP66zoS__1000) (Taken from either source context or sysl attributes)

**Comment by ashwinsajiv** [comment]
Addressed in PR #728
