### ISSUE TITLE
Move .sysl-tmp out of the repository

### ISSUE THREAD

**Issue by gkanz** [anz-bank/sysl#685]
The current location of this directory is creating the need to update `.gitconfig` for every repo with `/.sysl-tmp`. A better solution would be to not store this information in the repo.

**Comment by nydrani** [comment]
#693 Closes this issue.

**Comment by ChloePlanet** [comment]
The old LSP server creates a tmp folder to do sysl validations. And the whole #693 pr creates a new LSP server so the tmp dir doesn't even exist anymore.
