### ISSUE TITLE
Replace GolangCI with alternate option before 15th of April, 2020

### ISSUE THREAD

**Issue by cuminandpaprika** [anz-bank/sysl#687]
GoLangCI is being shut down 15th of April, 2020, so we will need to replace it with another SaaS option such as
- Reviewdog https://github.com/reviewdog/reviewdog
- Codeclimate https://codeclimate.com/

Announcement
https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e

**Comment by ChloePlanet** [comment]
https://golangci.com/r/github.com/anz-bank/sysl/pulls/788
