### ISSUE TITLE
OpenAPI 3 export support

### ISSUE THREAD

**Issue by matt-lock-anz** [anz-bank/sysl#745]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Current Sysl Version
```sh
Build:
  Version      : 0.7.1
  Git Commit   : cbe7b9a
  Date         : 2020-02-26T03:37:19Z
  Go Version   : go1.13.8 linux/amd64
  OS           : darwin/amd64
Runtime:
  GOOS/GOARCH  : darwin/amd64
  Go Version   : go1.13.8
```

### Use-cases
OpenAPI 3 is the successor to Swagger (OpenAPI 2) and a number of useful OpenAPI tools exist that only support v3. See https://openapi.tools/
If sysl export supported the OpenAPI 3 format then we can take advantage of the OpenAPI 3 tooling ecosystem

### Attempted Solutions
N/A

### References
N/A

**Comment by cuminandpaprika** [comment]
@matt-lock-anz Thanks for raising this, will be looking into implementing this as it's come up a few times recently

**Comment by cuminandpaprika** [comment]
Merged in https://github.com/anz-bank/sysl/pull/829
