### ISSUE TITLE
Review date/time support in generated Java code

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/sysl#79]
Currently, Sysl-generated Java code works with Joda-Time to managed date/time information. Java 8 has better date/time support and so we should think about what the right solution looks like.

**Comment by mhemphill-au** [comment]
Where I'm working at the moment there will be a need to support java 7 for a while yet, as well as java 9, therefore I would suggest providing support for both Joda and native Java types, and use some kind of feature toggle or configuration option to the java generator to switch between the two.
