### ISSUE TITLE
Sysl export to swagger not working

### ISSUE THREAD

**Issue by suipinglu** [anz-bank/sysl#794]
Hi everyone,
Want export the sysl file into Swagger format for the business. However, run into some error which i could not figure out.

Could someone please share some lights here?

Cheers.

```
syslgen export -v  --app-name=Bff --root . codegen/model/bff --format="swagger" --output=test.yaml 
```
Got the following response with a "v" mode
```
DEBU[0000] Logging: {loglevel:debug verbose:true}       
DEBU[0000] Attempting to load module:codegen/model/bff (root:.) 
WARN[0000] .sysl is not defined but root flag is defined in . 
DEBU[0000] Parsing: codegen/model/bff.sysl                
WARN[0001] Type matching failed none of the Swagger Types match 
WARN[0001] Error generating swagger for the application none of the Swagger Types match 
ERRO[0001] none of the Swagger Types match    
```

**Comment by cuminandpaprika** [comment]
@suipinglu Still investigating why the command above fails, but for now here's a workaround:
Change directory to `cd codegen/model`
`sysl export -v --app-name=Bff bff.sysl --format="swagger" --output=test.yaml`

**Comment by suipinglu** [comment]
> @suipinglu Still investigating why the command above fails, but for now here's a workaround:
> Change directory to `cd codegen/model`
> `sysl export -v --app-name=Bff bff.sysl --format="swagger" --output=test.yaml`

Hi Jack, still getting the same thing:
```
pwd
****omitted****/codegen/model

syslgen export -v --app-name=Bff bff.sysl --format="swagger" --output=test.yaml

DEBU[0000] Logging: {loglevel:debug verbose:true}
DEBU[0000] Attempting to load module:bff.sysl (root:)
WARN[0000] root and .sysl are undefined, . will be used instead
DEBU[0000] Parsing: bff.sysl
WARN[0001] Type matching failed none of the Swagger Types match
WARN[0001] Error generating swagger for the application none of the Swagger Types match
ERRO[0001] none of the Swagger Types match
```

**Comment by cuminandpaprika** [comment]
@suipinglu Would you be able to verify what version of sysl you're running with `sysl --version`?
