### ISSUE TITLE
Support Joda DateTime

### ISSUE THREAD

**Issue by anzdaddy** [anz-bank/sysl#80]
### Expected behaviour
Able to work with Joda DateTime or LocalTime, as appropriate.

### Actual behaviour
Only able to output a LocalTime.

### Steps to reproduce the behaviour
1. Write a sysl transform that uses the to_date() function.
2. Generate the Java transform.

### Additional thoughts.
Joda time is used in order to support Java 7. Java 8 has a significantly improved date/time support, so this might lead to a bigger change (#79).

**Comment by juliaogris** [comment]
@anzdaddy - I believe you said this was based on a misunderstanding. Can it be closed?

**Comment by anzdaddy** [comment]
This was based on a misunderstanding of an issue raised wrt to_date(). The original concern was that no to_datetime() was available, but since to_date() extracts a date from a datetime a counterpart doesn't make sense. #79 covers date/time support in general. Will close this.
