### ISSUE TITLE
Allow wildcard imports

### ISSUE THREAD

**Issue by joshcarp** [anz-bank/sysl#804]
`import *.sysl`
or 
`import dir/*/*.sysl`

**Comment by anz-gordonj7** [comment]
This is not a safe idea, It is always better to be explicit than implicit.

This could load up sysl files which the user didnt intent to be loaded (files which were copied for example for testing?) which could have very non-obvious side effects to the output module.

I would give this a very VERY strong NACK as something that should be implemented.

**Comment by anzdaddy** [comment]
Agreed, importing `*` is dangerous and rarely necessary. If a package contains many files intended to be used together, an aggregator file should perform all the imports explicitly and outside users can import that one file.
