### ISSUE TITLE
Could not install the v0.66.0 package

### ISSUE THREAD

**Issue by jecofang01** [anz-bank/sysl#805]
I try to install the latest sysl package with the command
```
go get -u -v github.com/anz-bank/sysl/cmd/sysl
```
But got the error as following
![image](https://user-images.githubusercontent.com/2755216/80053802-53524580-8550-11ea-9c27-568d0c249342.png)

**Comment by cuminandpaprika** [comment]
Hi @jecofang01 i'm able to reproduce the error, but it doesn't seem to stop installation of the sysl package. Are you encountering any other issues that's causing the installation to fail?

**Comment by nofun97** [comment]
@jecofang01 hi, it seems to be a dependency issues. Do you have a the library `github.com/getkin/kin-openapi` in your machine? We're using `v0.3.0`, please check if you have the same version.
