### ISSUE TITLE
Investigate the string cleaner and mermaidjs's accepted characters for a node name

### ISSUE THREAD

**Issue by ashwinsajiv** [anz-bank/sysl#814]

**Comment by cuminandpaprika** [comment]
This might be useful for future reference https://github.com/mermaid-js/mermaid/issues/407#issuecomment-329944735

**Comment by ashwinsajiv** [comment]
https://github.com/mermaid-js/mermaid/issues/1506
Raised an issue to add escaping of characters in class diagram.

**Comment by ashwinsajiv** [comment]
https://github.com/anz-bank/sysl/pull/923
This PR fixes the issue with the features that are supported by mermaid for now
