### ISSUE TITLE
Go generated import statements sometimes contain an extra `/`

### ISSUE THREAD

**Issue by anzboi** [anz-bank/sysl#833]
### Description

Sometimes generated code seems to contain an extra `/` which needs to be removed manually. I have only noticed this with sysl specs that import a swagger file. Ask @anzboi for the repo where I first noticed this problem

### Steps to Reproduce
As best as I can tell, this is how I produced the error. It may not occur for every swagger import

1. Use the sysl-go template to create a repo
2. Update the simple.sysl file to import your new swagger file
3. run `make`

Generated code contains imports like

```
import path/to/dependency//package
```

**Expected behavior:**

Imports should only contain a single `/` per path element.

**Actual behavior:**

Sometimes imports contain two

### Your Environments
```sh
$ sysl info
Build:
  Version      : 0.76.0
  Git Commit   : c89f026
  Date         : 2020-05-04T06:30:28Z
  Go Version   : go1.13.10 linux/amd64
  OS           : darwin/amd64
Runtime:
  GOOS/GOARCH  : darwin/amd64
  Go Version   : go1.13.10

$ sysl env
SYSL_MODULES=""
SYSL_PLANTUML=""
```

**Comment by andrewemeryanz** [comment]
Relocated to https://github.com/anz-bank/sysl-go/issues/118
