### ISSUE TITLE
Go codegen - consider nil getters for field access

### ISSUE THREAD

**Issue by anzboi** [anz-bank/sysl#834]
### Current Sysl Version
```sh
$ sysl info
Build:
  Version      : 0.76.0
  Git Commit   : c89f026
  Date         : 2020-05-04T06:30:28Z
  Go Version   : go1.13.10 linux/amd64
  OS           : darwin/amd64
Runtime:
  GOOS/GOARCH  : darwin/amd64
  Go Version   : go1.13.10
```

### Use-cases

Accessing optional fields in go generated code requires many nil checks.

```go
Object.Foo.Bar.Baz // if any one of the middle two is nil, panics
```

### Attempted Solutions

grpc generated code gets around this problem nicely using get methods that does a nil check and returns 0 value if Get is called on nil

```go
func (o *Object) GetFoo() *Foo {
    if o == nil {
        return nil
    }
    return o.Foo
}
```

This means in my code I can go straight to the object I'm trying to reach and do a single nil check there

```go
if Object.GetFoo().GetBar().GetBaz() == nil {
    // handle nil
}
// handle not nil
```

**Comment by anzdaddy** [comment]
obsolete
