### ISSUE TITLE
Define sysl GRPC representation

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl#846]
In order to build out `grpc` support within `sysl`, an authoritative document needs to exist that details how a `grpc` specification is represented in `sysl`.

Current work within this area includes the [protoc-gen-sysl](https://github.com/anz-bank/protoc-gen-sysl) plugin (a `protoc` plugin to generate `sysl` from a `grpc` specification) and some [early work](https://github.com/anz-bank/sysl/tree/master/demo/codegen/GRPCProtoGeneration) to generate a `grpc` specification from `sysl`.

The document must detail at least the following:
1. Which `grpc` features can be represented in `sysl` and to what extent.
2. How supported `grpc` features are represented in `sysl`.
3. What transformations are necessary (such as the renaming of identifiers) to support translation between formats.

**Comment by andrewemeryanz** [comment]
Linked issues:
`grpc` to `sysl`: https://github.com/anz-bank/sysl-go/pull/98
`sysl` to `grpc`: https://github.com/anz-bank/sysl/issues/847

**Comment by joshcarp** [comment]
Found here: https://github.com/anz-bank/protoc-gen-sysl#mapping-from-proto-to-sysl
