### ISSUE TITLE
Sysl Playground does not work

### ISSUE THREAD

**Issue by alecthegeek** [anz-bank/sysl#888]
### Description

Goto 

https://sysl.io/docs/byexample/rest-and-http/

then follow this link

http://anz-bank.github.io/sysl-playground/?input=Rm9vOgogICAgL2VuZHBvaW50OgogICAgICAgIFBPU1QgKG5ld1Bvc3QgPDogc3RyaW5nIFt+Ym9keV0pOgogICAgICAgICAgICByZXR1cm4gc3RyaW5nCiAgICAgICAgR0VUIChuZXdQb3N0IDw6IHN0cmluZyk6CiAgICAgICAgICAgIHJldHVybiBzdHJpbmcK&cmd=

### Steps to Reproduce

Select the above link

**Expected behavior:**

Not sure

**Actual behavior:**

![image](https://user-images.githubusercontent.com/14003/84627409-3b80b780-af2a-11ea-96f8-0e0dbbd1d95f.png)

### Your Environments

Version 83.0.4103.97 (Official Build) (64-bit)
Windows 10 Pro 1909

**Comment by ChloePlanet** [comment]
time estimated: less than a day

**Comment by alecthegeek** [comment]
cannot verify.
