### ISSUE TITLE
Add default value when SYSL_PLANTUML is unset

### ISSUE THREAD

**Issue by ChloePlanet** [anz-bank/sysl#919]
### Current Sysl Version
v0.123.0

### Use-cases
`export SYSL_PLANTUML=http://www.plantuml.com/plantuml` is required to generate diagram at present. 
Adding a default value to it if SYSL_PLANTUML is unset.

**Comment by anzdaddy** [comment]
Changing the default to a public service is dangerous, since it will result in accidental leakage of work product from organisations using Sysl internally. A better solution is to keep the default but provide helpful instructions in the error output if localhost:8080 doesn't work.
