### ISSUE TITLE
Combine type annotations

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl#966]
### Purpose

Combine annotations on `type` entitles in the same manner as `application` entitles.

### Problem

Given the following two files:

`parent.sysl`:
```
import child
App [~parent-ann]:
    !type T [~parent-ann]:
        ...
```
`child.sysl`:
```
App [~child-ann]:
    !type T [~child-ann]:
        ...
```

The following combined sysl is produced:
```
App [~parent-ann, ~child-ann]:
    !type T [~child-ann]:
        ...
```

### Suggested solution

Combine annotations on `type` entities in the same manner as `application` entities:

```
App [~parent-ann, ~child-ann]:
    !type T [~parent-ann, ~child-ann]:
        ...
```

**Comment by orlade-anz** [comment]
Novan is looking at a similar issue, assigned.
