### ISSUE TITLE
Syntax union issue

### ISSUE THREAD

**Issue by ericzhang6222** [anz-bank/sysl#976]
### Description
As https://sysl.io/docs/lang-spec/#union `!union string, int32` should work, but it can't actually.

### Steps to Reproduce
1. Created Sysl file demo.sysl
```
Project:
    App:
        Simple

Simple:
    !type User:
        id <: string
        ping <: StringOrInt32

    !union StringOrInt32:
        a
        b
    
    !alias a:
        string

    !alias b:
        int32

    !union string, int32
```
2. Run command `sysl datamodel -j Project -d demo.sysl`
### Expected behavior
It can run successfully and output diagram

### Actual behavior
It is crashed and output error:
```
$ sysl datamodel -j Project -d demo.sysl
line 20:11 mismatched input 'string' expecting {TEXT_LINE, Name, E_Name}
ERRO[0000] demo.sysl has syntax errors      
```
It can't pass Sysl syntax parsing.

And the alternative option is:
```
!union StringOrInt32:
        a
        b

!alias a:
        string
!alias b:
        int32
```

### Your Environment
```sh
$ sysl info
Build:
  Version         :  v0.155.0
  Git Commit   : 7f4486576e79474836ac6e8377458aab7239dd9e
  Date              : 2020-07-29T08:14:51Z
  Go Version   : go1.14 darwin/amd64
  OS                 : darwin/amd64
```

**Comment by ChloePlanet** [comment]
Related: https://github.com/anz-bank/sysl/pull/170

**Comment by ericzhang6222** [comment]
Fixed by https://github.com/anz-bank/sysl-website/pull/58

**Comment by andrewemeryanz** [comment]
@ChloePlanet Is the implementation by design or should it be considered as a feature to add? Could we support the following syntax:
```
!alias StringInt:
    string
    int
```

**Comment by anzdaddy** [comment]
It's an implementation gap. We should support unions of any type, including aliases and direct primitives:

```sysl
!uniom StringInt:
    string
    int
```

**Comment by ericzhang6222** [comment]
Avro to Sysl transformation is depending on this issue, change priority to P0 to fix ASAP.

**Comment by andrewemeryanz** [comment]
This fix also needs to support sequences and sets:

```sysl
!union StringSequenceAddressSet:
    sequence of string
    set of Address
```

**Comment by ericzhang6222** [comment]
One more fixing to support:
```
!alias md5 [~fixed, namespace="com.example"]:
    bytes(16)
```
This is not union change, but added here for tracking, will raise another issue later.
